[workspace]
members = ["indexer", "database", "circulating-supply"]

[workspace.dependencies]
near-jsonrpc-client = "0.10.1"
near-primitives = "0.23.0"
near-crypto = "0.23.0"
near-chain-configs = "0.23.0"
near-indexer-primitives = "0.23.0"
near-jsonrpc-primitives = "0.23.0"
